---
version: 2
project_name: otpgen
before:
  hooks:
    - go mod tidy
    - mkdir -p completions
    - sh -c "go run . completion bash > completions/otpgen.bash"
    - sh -c "go run . completion zsh > completions/otpgen.zsh"
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - completions/*
      - README*
      - LICENSE*
homebrew_casks:
  - name: otpgen
    repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://containeroo.ch
    description: Simple CLI tool to generate OTP tokens
    license: GNU General Public License v3.0
    binaries:
      - otpgen
    completions:
      bash: completions/otpgen.bash
      zsh: completions/otpgen.zsh
    hooks:
      post:
        install: >-
          system_command "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "#{staged_path}/otpgen"],
          must_succeed: false
