---
project_name: otpgen
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
brews:
  - name: otpgen
    tap:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://containeroo.ch
    description: Simple CLI tool to generate OTP tokens
    license: GNU General Public License v3.0
    test: |
      system "#{bin}/otpgen version"
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "otpgen"
